// example for reference
{
  housrApp:{

    - listings:{

        -roomates:{
          //firebase reference childkey is autogenerated
          -childkey:{
            postId: 0001,
            user: 'bigfatwoman',


          }
        }


        -listings:{

          -childkey:{
            postId: 0001,
            user: 'bigfatwoman',
            type: '1 BR 1 BA',
            available: true,
            price: 2500,
            location: '250 conway tweedy street',
            date_posted: '2017-01-01 etc',
            post_title: 'nice apartment in mid heights',
            post_description: 'lorem ipsum shibigoagagage',
            images: 'url'


          }


        }
    }

  }




}
